### PR TITLE
fix #2 handle the errors

### LINKED ISSUE #2: Compilation errors are not handled
Hi, I noticed gulp-rollup-each outputs unhandled promise rejections like the following log if the compiled code has some syntax errors.

```bash
(node:3864) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unexpected token
```

 I guess it is caused because gulp-rollup-each currently does not handle the errors from `rollup`.
Can we solve this problem so that providing readable errors?

### PR DESCRIPTION
**Pull request by ko-yelie**
fix #2
@ktsn Could you please check it?

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -20,19 +23,25 @@ module.exports = function (arg1, arg2) {
...
+
+          if (createSourceMap) {
+            result.map.file = entry
+            result.map.sources = result.map.sources.map(source => path.relative(file.cwd, source))
+            applySourceMap(file, result.map)
+          }
+
+          cb(null, file)
+        }).catch(err => {
+          process.nextTick(() => {
```
Comment (ktsn) [inline lib/index.js]: Why do we need to use `nextTick` here?

File: lib/index.js [hunk 2]
```diff
@@ -20,19 +23,25 @@ module.exports = function (arg1, arg2) {
...
+            this.emit('error', new PluginError(PLUGIN_NAME, err))
+            cb(null, file)
```
Comment (ktsn) [inline lib/index.js]: In the context of Node.js, the error should be passed to the 1st argument of callback if it exists. Also I wonder that we should pass the `file` to the 2nd arugment of the callback since the processing is failed when it enters in this block.

I think we can simply write like below:

```js
cb(new PluginError(PLUGIN_NAME, err))
```

File: lib/index.js (hunk 1 above)
Comment (ko-yelie) [reply lib/index.js]: I think it is not necessary.
他のコードを参考にしたときにそのまま使ってしまいました。

File: lib/index.js (hunk 2 above)
Comment (ko-yelie) [reply lib/index.js]: Oh, it is awesome code!
I understand. I'm going to use it.
https://github.com/gulpjs/gulp/tree/master/docs/writing-a-plugin#what-it-does

**Comment by ko-yelie** [comment]
@ktsn I changed code. Please check again.

**Comment by ktsn** [comment]
LGTM 👍

**Comment by ko-yelie** [comment]
Thanks!
